language: php

php:
  - 7.2.28
  - 7.3.15
  - 7.4.3

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction
  - mkdir -p example/idp_metadata
  - php bin/download_idp_metadata.php ./example/idp_metadata

script:
  - find . | grep 'php$' | grep -v vendor | grep -v tests | xargs ./vendor/bin/phpcs --standard=PSR2
  - vendor/bin/phpunit --stderr tests
